import { Injectable } from '@nestjs/common';
import * as puppeteer from 'puppeteer';
import { Task } from '../task/entities/task.entity';
import { Project } from '../project/entities/project.entity';
import { User } from '../users/entities/user.entity';

@Injectable()
export class PdfService {
  async generateDailyReportPdf(data: any): Promise<Buffer> {
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    try {
      const page = await browser.newPage();
      
      // Generate HTML content
      const htmlContent = this.generateHtmlContent(data);
      
      // Set content and wait for network idle
      await page.setContent(htmlContent);
      await page.waitForNetworkIdle();

      // Generate PDF
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: {
          top: '20px',
          right: '20px',
          bottom: '20px',
          left: '20px'
        }
      });

      // Convert Uint8Array to Buffer
      return Buffer.from(pdfBuffer);
    } finally {
      await browser.close();
    }
  }

  private generateHtmlContent(data: any): string {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
          }
          .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
            text-align: center;
          }
          .report-section {
            margin-bottom: 20px;
            padding: 15px;
            border: 1px solid #dee2e6;
            border-radius: 5px;
          }
          .stat-item {
            margin: 10px 0;
            padding: 5px 0;
          }
          .footer {
            margin-top: 20px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            font-size: 0.9em;
            color: #6c757d;
            text-align: center;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
          }
          th, td {
            padding: 8px;
            border: 1px solid #dee2e6;
            text-align: left;
          }
          th {
            background-color: #f8f9fa;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Daily Report</h1>
          <p>Generated on: ${new Date().toLocaleDateString()}</p>
        </div>

        ${data.totalTasks ? `
        <div class="report-section">
          <h2>Task Completion Rate</h2>
          <div class="stat-item">Total Tasks: ${data.totalTasks}</div>
          <div class="stat-item">Completed Tasks: ${data.completedTasks}</div>
          <div class="stat-item">Completion Rate: ${data.completionRate}%</div>
          ${data.statusBreakdown ? `
          <h3>Status Breakdown</h3>
          <table>
            <tr>
              <th>Status</th>
              <th>Count</th>
            </tr>
            ${data.statusBreakdown.map(item => `
              <tr>
                <td>${item.status}</td>
                <td>${item.count}</td>
              </tr>
            `).join('')}
          </table>
          ` : ''}
        </div>
        ` : ''}

        ${data.tasksCompleted ? `
        <div class="report-section">
          <h2>Daily Summary</h2>
          <div class="stat-item">Tasks Completed Today: ${data.tasksCompleted}</div>
          <div class="stat-item">Tasks Created Today: ${data.tasksCreated}</div>
          <div class="stat-item">Projects Completed Today: ${data.projectsCompleted}</div>
          <div class="stat-item">Projects Created Today: ${data.projectsCreated}</div>
          <div class="stat-item">Active Users Today: ${data.activeUsers}</div>
        </div>
        ` : ''}

        <div class="footer">
          <p>This is an automated report generated by the Task Management System.</p>
        </div>
      </body>
      </html>
    `;
  }
} 